# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/glacier/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/glacier/proprietary/libaudioalsa.so:obj/lib/libaudioalsa.so \
    vendor/htc/glacier/proprietary/libcamera.so:/obj/lib/libcamera.so \
    vendor/htc/glacier/proprietary/libv8.so:system/lib/libv8.so \
    vendor/htc/glacier/proprietary/libv8.so:obj/lib/libv8.so


# All the blobs necessary for glacier
PRODUCT_COPY_FILES += \
    vendor/htc/glacier/proprietary/akmd:/system/bin/akmd \
    vendor/htc/glacier/proprietary/bma150_usr:/system/bin/bma150_usr \
    vendor/htc/glacier/proprietary/htc_ebdlogd:/system/bin/htc_ebdlogd \
    vendor/htc/glacier/proprietary/bcm4329_aps.bin:/system/bin/bcm4329_aps.bin \
    vendor/htc/glacier/proprietary/bcm4329_mfg.bin:/system/bin/bcm4329_mfg.bin \
    vendor/htc/glacier/proprietary/bcm4329_sta.bin:/system/bin/bcm4329_sta.bin \
    vendor/htc/glacier/proprietary/logcat2:/system/bin/logcat2 \
    vendor/htc/glacier/proprietary/rmt_storage:/system/bin/rmt_storage \
    vendor/htc/glacier/proprietary/snd3254:/system/bin/snd3254 \
    vendor/htc/glacier/proprietary/AudioBTID.csv:/system/etc/AudioBTID.csv \
    vendor/htc/glacier/proprietary/libaudioalsa.so:/system/lib/libaudioalsa.so \
    vendor/htc/glacier/proprietary/libgemini.so:/system/lib/libgemini.so \
    vendor/htc/glacier/proprietary/libhtc_acoustic.so:/system/lib/libhtc_acoustic.so \
    vendor/htc/glacier/proprietary/libhtc_ril.so:/system/lib/libhtc_ril.so \
    vendor/htc/glacier/proprietary/librilswitch.so:/system/lib/librilswitch.so \
    vendor/htc/glacier/proprietary/libganril.so:/system/lib/libganril.so \
    vendor/htc/glacier/proprietary/libmmipl.so:/system/lib/libmmipl.so \
    vendor/htc/glacier/proprietary/libmmjpeg.so:/system/lib/libmmjpeg.so \
    vendor/htc/glacier/proprietary/libcamera.so:/system/lib/libcamera.so \
    vendor/htc/glacier/proprietary/libposteffect.so:/system/lib/libposteffect.so \
    vendor/htc/glacier/proprietary/snd3254:/system/bin/snd3254 \
    vendor/htc/glacier/proprietary/lsc_camera:/system/bin/lsc_camera \
    vendor/htc/glacier/proprietary/liboemcamera.so:/system/lib/liboemcamera.so \
    vendor/htc/glacier/proprietary/awb_camera:/system/bin/awb_camera \
    vendor/htc/glacier/proprietary/gps.glacier.so:/system/lib/hw/gps.glacier.so \
    vendor/htc/glacier/proprietary/libbcc.so:/system/lib/libbcc.so 

#Firmware
PRODUCT_COPY_FILES += \
    vendor/htc/glacier/firmware/bcm4329.hcd:/system/vendor/firmware/bcm4329.hcd \
    vendor/htc/glacier/firmware/fw_bcm4329.bin:/system/vendor/firmware/fw_bcm4329.bin \
    vendor/htc/glacier/firmware/fw_bcm4329_apsta.bin:/system/vendor/firmware/fw_bcm4329_apsta.bin \
    vendor/htc/glacier/firmware/fw_bcm4329_p2p.bin:/system/vendor/firmware/fw_bcm4329_p2p.bin


# FIle for adreno
PRODUCT_COPY_FILES += \
    vendor/htc/glacier/proprietary/system/etc/firmware/a225_pfp.fw:/system/etc/firmware/a225_pfp.fw \
    vendor/htc/glacier/proprietary/system/etc/firmware/a225_pm4.fw:/system/etc/firmware/a225_pm4.fw \
    vendor/htc/glacier/proprietary/system/etc/firmware/a225p5_pm4.fw:/system/etc/firmware/a225p5_pm4.fw \
    vendor/htc/glacier/proprietary/system/etc/firmware/a300_pfp.fw:/system/etc/firmware/a300_pfp.fw \
    vendor/htc/glacier/proprietary/system/etc/firmware/a300_pm4.fw:/system/etc/firmware/a300_pm4.fw \
    vendor/htc/glacier/proprietary/system/etc/firmware/leia_pfp_470.fw:/system/etc/firmware/leia_pfp_470.fw \
    vendor/htc/glacier/proprietary/system/etc/firmware/leia_pm4_470.fw:/system/etc/firmware/leia_pm4_470.fw \
    vendor/htc/glacier/proprietary/system/etc/firmware/yamato_pfp.fw:/system/etc/firmware/yamato_pfp.fw \
    vendor/htc/glacier/proprietary/system/etc/firmware/yamato_pm4.fw:/system/etc/firmware/yamato_pm4.fw \
    vendor/htc/glacier/proprietary/system/lib/egl/egl.cfg:/system/lib/egl/egl.cfg \
    vendor/htc/glacier/proprietary/system/lib/egl/eglsubAndroid.so:/system/lib/egl/eglsubAndroid.so \
    vendor/htc/glacier/proprietary/system/lib/egl/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \
    vendor/htc/glacier/proprietary/system/lib/egl/libGLES_android.so:/system/lib/egl/libGLES_android.so \
    vendor/htc/glacier/proprietary/system/lib/egl/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/htc/glacier/proprietary/system/lib/egl/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \
    vendor/htc/glacier/proprietary/system/lib/egl/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \
    vendor/htc/glacier/proprietary/system/lib/libC2D2.so:/system/lib/libC2D2.so \
    vendor/htc/glacier/proprietary/system/lib/libgsl.so:/system/lib/libgsl.so \
    vendor/htc/glacier/proprietary/system/lib/libOpenVG.so:/system/lib/libOpenVG.so \
    vendor/htc/glacier/proprietary/system/lib/libsc-a2xx.so:/system/lib/libsc-a2xx.so

